input {
  beats {
    port => 5044
  }
}

filter {
  if "juice-shop" in [container][name] {
    grok {
      match => {
        "message" => "%{IPORHOST:client_ip} .* \"%{WORD:method} %{URIPATHPARAM:url} HTTP/%{NUMBER:http_version}\" %{NUMBER:status}"
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "juice-shop-%{+YYYY.MM.dd}"
  }
}
